version: "3"

services:
  # Note: requires .env file with POSTGRES_USER and POSTGRES_PASSWORD

  orion:
    image: registry.gitlab.com/libdemsoftware/registr/orion
    container_name: orion
    depends_on:
      - postgres
    environment:
      - PREFECT_ORION_DATABASE_CONNECTION_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host.docker.internal:5432/orion
    ports:
      - 4200:4200
    restart: always

  postgres:
    image: postgres
    container_name: orion_postgres
    volumes:
      - ~/oriondb:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=orion
    ports:
      - 5432:5432
    restart: always

  # temporary container to create storage
  orion_setup:
    image: registry.gitlab.com/libdemsoftware/registr/orion
    container_name: orion_setup
    depends_on:
      - orion
    command: sh orion_setup.sh
    # in quotes as no gets read as False
    restart: "no"
