"""
This file is automatically generated by the autogen package.
Please edit the marked area only. Other areas will be
overwritten when autogen is rerun.
"""

from setuptools import setup

params = dict(
    name="pipex",
    description="pipex",
    version="1.0.0",
    url="http://github.com/simonm3/pipex.git",
    install_requires=["prefect", "PyYAML"],
    packages=["pipex", "pipex.prefect"],
    package_data={},
    include_package_data=True,
    py_modules=[],
    scripts=None,
)

########## EDIT BELOW THIS LINE ONLY ##########


########## EDIT ABOVE THIS LINE ONLY ##########

setup(**params)
